### ISSUE TITLE
Dependency conflict with nchelpers

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/thunderbird#48]
When I go to install `thunderbird` dependencies to a clean virtual environment with the following command, I get a dependency conflict for `nchelpers`.

```bash
(venv) james@basalt:~/code/git/thunderbird$ pip install -r requirements.txt  -r test_requirements.txt -r notebooks/demo_requirements.txt
...
ERROR: nchelpers 5.5.6 has requirement netCDF4==1.3, but you'll have netcdf4 1.5.3 which is incompatible.
```

This is problematic both from two perspectives. The first is obviously that we should not have a dependency conflict. However, during a cursory investigation, I wasn't able to figure out where the dependency was coming from.

`nchelpers` is directly used by the package, but it is not declared as a dependency, which is the second problem.

```bash
james@basalt:~/code/git/thunderbird$ find ./ -name "*.py" -exec grep -Hi nchelpers '{}'  \;
./thunderbird/utils.py:from nchelpers import CFDataset
./thunderbird/processes/wps_update_metadata.py:from nchelpers import CFDataset
./thunderbird/processes/wps_split_merged_climos.py:from nchelpers import CFDataset
./thunderbird/processes/wps_generate_climos.py:from nchelpers import CFDataset, standard_climo_periods
...
```

```
james@basalt:~/code/git/thunderbird$ find ./ -maxdepth 3 -name "*.txt" -exec grep -Hi nchelpers '{}'  \;
james@basalt:~/code/git/thunderbird$ 
```

A little work should be done to declare this dependency in one of the requirements files and ensure that it doesn't conflict with other recursive dependencies.

**Comment by nikola-rados** [comment]
It is interesting that this _just_ started happening.  I'm not sure why it wasn't complaining about this before.  

I worked with @corviday a bit on issue #41 and I found that there was some inconsistency between the behaviour of the netcdf files. The solution was to bump the `netCDF4` version in here to the most up-to-date to match the version found in the jupyter env. I wonder if my update of the `_FillValue`'s in the test files was actually enough to stop the issue from happening in the first place. 

If that is the case we _could_ remove the requirement from this repo.  Although it would be nice to keep things consistent since the error we got on jupyter were not showing up for us locally.

**Comment by nikola-rados** [comment]
@jameshiebert I have tested out removing `netCDF4==1.5.3` from the requirements and everything runs fine.  My only concern about doing this is that our CI may not uncover the same errors as running in the jupyter env (as discovered in the previous issue). Perhaps that is _ok_ since we could ensure we run through the demo after applying changes? Not sure I love the sound of that though.

> A little work should be done to declare this dependency in one of the requirements files and ensure that it doesn't conflict with other recursive dependencies.

So the `nchelpers` dependency comes from the `ce-dateprep` package. I'm not sure I understand what the benefit would be to including the package in the `requirements.txt` would be, could you explain?

**Comment by jameshiebert** [comment]
Yeah, so I was able to run the demo by manually downgrading the dependency to `netCDF4==1.3` to match the `nchelpers` dependency. But I think that we should do quite a bit more testing before declaring this a permanent solution.

I'd be *more* keen to explore the potential for upgrading `netCDF4` in `nchelpers` to 1.5... but again, that will require a lot of care and attention to detail.

> I'm not sure I understand what the benefit would be to including the package in the requirements.txt would be, could you explain?

Well, at a *minimum*, packages should declare the dependencies that they import directly, which is the case here. `thunderbird` directly imports `nchelpers` in several modules, so it should be included both as an abstract dependency in the `setup.py` and a concrete dependency in `requirements.txt`.

**Comment by nikola-rados** [comment]
> I'd be more keen to explore the potential for upgrading netCDF4 in nchelpers to 1.5... but again, that will require a lot of care and attention to detail.

That was a suggestion I made as well.  I think it is the best solution but also the most time consuming. Should we at least open an issue in `nchelpers` to explore it a bit?

> `thunderbird` directly imports `nchelpers` in several modules...

OH, that makes complete sense. We are directly importing and using a package we indirectly install.
